language: node_js

cache:
  npm: false
  directories:
    - "~/.pnpm-store"
    
before_install:
  - npm install -g pnpm
  - pnpm config set store-dir ~/.pnpm-store
  
install:
  - pnpm install

script:
  - pnpm run update-club-info
