[tool.poetry]
name = "enspire"
version = "0.1.0"
description = ""
authors = ["qwerzl <me@qwerzl.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
prisma = "^0.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
